# Generated by Django 5.0.1 on 2024-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_aluno_cpf_alter_aluno_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
